//
// Terminal12.h
// Font library
// ----------------------------------
// Developed with embedXcode http://embedXcode.weebly.com
//
// Project LCD BoosterPack
// Created by Rei VILO on 26/05/12
// Copyright (c) 2012 http://embeddedcomputing.weebly.com
// Licence CC = BY SA NC
//
//
// WARNING: This Font Require X-GLCD Lib.
// You can not use it with MikroE GLCD Lib.
//
// Font Generated by MikroElektronika GLCD Font Creator 1.2.0.0
// MikroElektronika 2011 http://www.mikroe.com
//
// GLCD FontName : Terminal11x16
// GLCD FontSize : 11 x 16
//

#ifndef TERMINAL12_H
#define TERMINAL12_H

extern rom const unsigned char Terminal11x16[96][22];

#endif
