//
// Terminal6.h
// Font library
// ----------------------------------
// Developed with embedXcode
//
// Project LCD BoosterPack
// Created by Rei VILO on 26/05/12
// Copyright (c) 2012 http://embeddedcomputing.weebly.com
// Licence CC = BY SA NC
//
//
// WARNING: This Font is usable only with MikroE GLCD Lib.
// X-GLCD Lib does not handle this font.
//
// Font Generated by MikroElektronika GLCD Font Creator 1.2.0.0
// MikroeElektronika 2011 http://www.mikroe.com
//
// GLCD FontName : Terminal6x8
// GLCD FontSize : 5 x 8
//

#ifndef TERMINAL6_H
#define TERMINAL6_H


extern rom const unsigned char Terminal6x8[96][5];


#endif

